// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	// Replace this comment with your code

	int Ntimes = Integer.parseInt(args[0]);

	if (Ntimes <= 0 ) {
		System.out.println("Please provide a positive integer as input.");
	} else {
		int numberBig = 0;

	for (int i = 0; i<Ntimes; i++ ) {
		double flip = Math.random();

		if (flip > 0.5) {
			numberBig++;	
		 	} 
		}

	int numberSmall = Ntimes - numberBig;

        if (numberSmall == 0 || numberBig == 0) {
            System.out.println("> 0.5: " + numberBig);
            System.out.println("<= 0.5: " + numberSmall);
        } else {

	double Ratio = (double) numberBig/numberSmall;

	System.out.println("> 0.5:  "+numberBig);
	System.out.println("<= 0.5: "+(numberSmall));
	System.out.println("Ratio:  "+(Ratio));
			}
		}
	}
}
